### ISSUE TITLE
Does this work with community edition

### ISSUE THREAD

**Issue by sumitt** [Ricksoft-OSS/audit-log-browser#4]
Dear Sir/Madam,

Does this module work with alfresco community edition 5.2 or any other version?

Thanks for your support.

- Sumit

**Comment by silverskyvicto** [comment]
Hi @sumitt Thank you for comment.

First, the Audit Log Browser uses Alfresco's v1 REST API.
This is an API implemented from ACS 5.2.2, so theoretically it will work with ACS 5.2.2 or higher or equivalent Community Edition.

At present we are working on the Alfresco community Edition 6.0 platform.
So, it has been confirmed that it works with Alfresco community Edition 6.0.

In the case of Alfresco Community 5.2, `https://api-explorer.alfresco.com/api-explorer/#!/groups/listGroups` can be used, so the v1 REST API itself seems to be implemented.
So, I think that you can use it if you can set up the audit application.
